### ISSUE TITLE
web origins in overridden realm

### ISSUE THREAD

**Issue by ryandawsonuk** [Alfresco/alfresco-identity-service#22]
Activiti is currently using https://github.com/Activiti/activiti-cloud-charts/tree/master/activiti-keycloak to wrap the stable/keycloak chart and inject the activiti realm. We'd like to use alfresco-identity-service instead.

We could put a value called `ALFRESCO_CLIENT_REDIRECT_URIS` in our acitivit-realm.json file and use the replace mechanism in the alfresco-identity-service chart. It's not ideal that then the realm file is no longer valid json until it gets loaded by helm (i.e. the file in github isn't valid in itself) but I think we could live with that for now. But we'd need to set origins as well as redirect uris to match what we're currently doing with sed.

**Comment by rgauss** [comment]
> It's not ideal that then the realm file is no longer valid json until it gets loaded by helm (i.e. the file in github isn't valid in itself)

Agreed. That was a compromise in order to quickly get these changes in.  I suppose we could try changing the realm file to contain:
```
"redirectUris": [ "ALFRESCO_CLIENT_REDIRECT_URIS" ]
```

then change the replace to:
```
replace "[ \"ALFRESCO_CLIENT_REDIRECT_URIS\" ]" .Values.client.alfresco.redirectUris
```

If that works we could use the same approach for `webOrigins`.

**Comment by ryandawsonuk** [comment]
Something I'd like to try is setting the realm file to contain:

"redirectUris": " {{ .Values.client.alfresco.redirectUris }}",

And loading the file with:

"alfresco-realm.json": {{ tpl (.Files.Get "alfresco-realm.json") . | b64enc | quote }}

Like in https://stackoverflow.com/questions/47595295/how-do-i-load-multiple-templated-config-files-into-a-helm-chart/52009228#52009228

**Comment by jottley** [comment]
Shadowed to [AUTH-217](https://issues.alfresco.com/jira/browse/AUTH-217)

**Comment by ryandawsonuk** [comment]
Managed to try this approach out and it does seem to work - https://github.com/Activiti/activiti-cloud-charts/pull/32/files

**Comment by svidrascu** [comment]
This looks great Ryan, this brings us closer to a common identity chart also from my point of view. I'll look to add this in identity.
