### ISSUE TITLE
move to new keycloak chart

### ISSUE THREAD

**Issue by ryandawsonuk** [Alfresco/alfresco-identity-service#23]
Activiti is in the process of moving to the keycloak 4.1.0.Final. It would be good if this keycloak chart dep could therefore be moved to 3.1.0. Is there a plan to do this anyway?

**Comment by rgauss** [comment]
We have some automated testing work we'd need to get done before making that big of a change, some of which has already been started.

I've created [AUTH-175](https://issues.alfresco.com/jira/browse/AUTH-175) (for those that have access) to track considering the upgrade in the future.

**Comment by melahn** [comment]
Once we get the automated testing work done, is there any reason not to step up to the latest version which is **keycloak-4.5.0.Final**?

**Comment by melahn** [comment]
ok then let's stick with Keycloak 4.2.1.Final as picked up by 3.4.1 of the chart.

**Comment by melahn** [comment]
In anticipation of Identity Service 1.0, we have have stepped up to 4.2.1.Final now (via chart keycloak:3.4.2) so I am closing this.
