### ISSUE TITLE
make clientId configurable from values file

### ISSUE THREAD

**Issue by ryandawsonuk** [Alfresco/alfresco-identity-service#73]
for https://github.com/Activiti/activiti-cloud-charts/pull/45#issuecomment-464785175

**Comment by svidrascu** [comment]
Closing this as it seems it is not actually needed. Feel free to reopen @ryandawsonuk if i'm wrong.

**Comment by ryandawsonuk** [comment]
It's not needed for Activiti to be able to use AIS. My impression is that it will be more difficult to get APS to use the common base realm without this change as APS is using a client called `activiti` and seems to have more configuration that could be reliant on that name.

**Comment by ryandawsonuk** [comment]
Actually APS needs multiple clients so this would have to be made more flexible. Could we reopen this (I don't have permission)?

**Comment by ryandawsonuk** [comment]
Actually we could now close this as a duplicate of https://github.com/Alfresco/alfresco-identity-service/issues/81 - sorry to go round in circles
