### ISSUE TITLE
AUTH-257 - support having APS2 use common base realm

### ISSUE THREAD

**Issue by ryandawsonuk** [Alfresco/alfresco-identity-service#81]
Have submitted https://github.com/Alfresco/alfresco-identity-service/pull/80 as APS [needs multiple clients and roles for each](https://github.com/Alfresco/alfresco-identity-service/issues/73).

There is a more radical alternative path available here, which would be to replace the use of the realm in the secret with:

` "alfresco-realm.json": {{ .Values.realm | toJson | b64enc | quote }}`

That would move all of the realm configuration into the values file. @mteodori realised that keycloak actually defaults a lot if you don't specify it so we could get away with removing a lot of the realm config that is currently present. There then wouldn't be any common base config but seeing what config was being supplied by the activiti and APS charts would be simpler. 

But I'm assuming that we do want there to be common base config supplied at the AIS level.

**Comment by rgauss** [comment]
I think putting the realm contents in the values file would lead to an overly complicated values file that would be irrelevant for those that want to export then import an existing realm file for upgrades and migrations.

> @mteodori realised that keycloak actually defaults a lot if you don't specify it so we could get away with removing a lot of the realm config that is currently present

If so we should certainly consider trimming down the realm file.

**Comment by rgauss** [comment]
Created AUTH-260 to track the trimming of the realm file separately.

Closing this PR.

**Comment by ryandawsonuk** [comment]
@rgauss I guess you know the PR linked to this is awaiting review? Just confused by the "Closing this PR" comment.

**Comment by rgauss** [comment]
Yes, sorry, meant "Closing this issue", edited comment.
