### ISSUE TITLE
Does alfresco keycloak supports kerberos authentication?

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-identity-service#85]
Does alfresco keycloak supports kerberos authentication? Otherwise how this idnetity service works with office integration with Alfresco?

**Comment by rgauss** [comment]
Hi Venu,

While Kerberos is technically possible with the Identity Service it is not a tested, supported means of authentication at the Identity Service at this time.

Support for Kerberos and Office Services is actively being considered for future releases.

Stay tuned.
